; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; General settings
AppName=Jared Transcription App
AppVersion=1.2
DefaultDirName={pf}\JTA - Parsnip
DefaultGroupName=JTA - Parsnip
OutputDir="C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\dist"
OutputBaseFilename=JTA_Parsnip_Installer
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64  
; For 64-bit installation
DisableProgramGroupPage=yes

[Files]
; Include all required files for the application
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\jta_windows.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\ffmpeg\*"; DestDir: "{app}\ffmpeg"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\model\*" ; DestDir: "{app}\model"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\vosk\*" ; DestDir: "{app}\vosk"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\share\*"; DestDir: "{app}\share"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\python3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\python310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\build\exe.win-amd64-3.10\frozen_application_license.txt"; DestDir: "{app}"; Flags: ignoreversion

Source: "C:\users\joeroberts\Documents\MarcyLabWorld\environment\Converter App\icons\jta_logo.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Create shortcut in the Start Menu
Name: "{group}\JTA - Parsnip"; Filename: "{app}\jta_windows.exe"; IconFilename: "{app}\jta_logo.ico"
; Create shortcut on Desktop
Name: "{commondesktop}\JTA - Parsnip"; Filename: "{app}\jta_windows.exe"; IconFilename: "{app}\jta_logo.ico"