name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_Freeze

      - name: Build macOS app
        run: |
          python setup.py build
          ls -la build/

      - name: Archive macOS build
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_Freeze

      - name: Build Windows exe
        run: |
          python setup.py build
          ls -la build/

      - name: Archive Windows build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/
